
export const countries = [
    {"name": "Afghanistan", "code": "AF", "icon": "afghanistan.png"},
    {"name": "Åland Islands", "code": "AX", "icon": "alandislands.png"},
    {"name": "Albania", "code": "AL", "icon": "albania.png"},
    {"name": "Algeria", "code": "DZ", "icon": "algeria.png"},
    {"name": "Andorra", "code": "AD", "icon": "andorra.png"},
    {"name": "Angola", "code": "AO", "icon": "angola.png"},
    {"name": "Anguilla", "code": "AI", "icon": "anguilla.png"},
    {"name": "Antigua and Barbuda", "code": "AG", "icon": "antiguaandbarbuda.png"},
    {"name": "Argentina", "code": "AR", "icon": "argentina.png"},
    {"name": "Armenia", "code": "AM", "icon": "armenia.png"},
    {"name": "Aruba", "code": "AW", "icon": "aruba.png"},
    {"name": "Australia", "code": "AU", "icon": "australia.png"},
    {"name": "Austria", "code": "AT", "icon": "austria.png"},
    {"name": "Azerbaijan", "code": "AZ", "icon": "azerbaijan.png"},
    {"name": "Bahamas", "code": "BS", "icon": "bahamas.png"},
    {"name": "Bahrain", "code": "BH", "icon": "bahrain.png"},
    {"name": "Bangladesh", "code": "BD", "icon": "bangladesh.png"},
    {"name": "Barbados", "code": "BB", "icon": "barbados.png"},
    {"name": "Belarus", "code": "BY", "icon": "belarus.png"},
    {"name": "Belgium", "code": "BE", "icon": "belgium.png"},
    {"name": "Belize", "code": "BZ", "icon": "belize.png"},
    {"name": "Benin", "code": "BJ", "icon": "benin.png"},
    {"name": "Bermuda", "code": "BM", "icon": "bermuda.png"},
    {"name": "Bhutan", "code": "BT", "icon": "bhutan.png"},
    {"name": "Bolivia", "code": "BO", "icon": "bolivia.png"},
    {"name": "Bosnia and Herzegovina", "code": "BA", "icon": "bosniaandherzegovina.png"},
    {"name": "Botswana", "code": "BW", "icon": "botswana.png"},
    {"name": "Bouvet Island", "code": "BV", "icon": "bouvetisland.png"},
    {"name": "Brazil", "code": "BR", "icon": "brazil.png"},
    {"name": "British Indian Ocean Territory", "code": "IO", "icon": "britishindianoceanterritory.png"},
    {"name": "Brunei Darussalam", "code": "BN", "icon": "brunei.png"},
    {"name": "Bulgaria", "code": "BG", "icon": "bulgaria.png"},
    {"name": "Burkina Faso", "code": "BF", "icon": "burkinafaso.png"},
    {"name": "Burundi", "code": "BI", "icon": "burundi.png"},
    {"name": "Cambodia", "code": "KH", "icon": "cambodia.png"},
    {"name": "Cameroon", "code": "CM", "icon": "cameroon.png"},
    {"name": "Canada", "code": "CA", "icon": "canada.png"},
    {"name": "Cape Verde", "code": "CV", "icon": "capeverde.png"},
    {"name": "Cayman Islands", "code": "KY", "icon": "caymanislands.png"},
    {"name": "Central African Republic", "code": "CF", "icon": "centralafricanrepublic.png"},
    {"name": "Chad", "code": "TD", "icon": "chad.png"},
    {"name": "Chile", "code": "CL", "icon": "chile.png"},
    {"name": "China", "code": "CN", "icon": "china.png"},
    {"name": "Christmas Island", "code": "CX", "icon": "christmasislands.png"},
    {"name": "Cocos (Keeling) Islands", "code": "CC", "icon": "cocosislands.png"},
    {"name": "Colombia", "code": "CO", "icon": "colombia.png"},
    {"name": "Comoros", "code": "KM", "icon": "comoros.png"},
    {"name": "Congo, The Democratic Republic of the", "code": "CD", "icon": "congo.png"},
    {"name": "Cook Islands", "code": "CK", "icon": "cookislands.png"},
    {"name": "Costa Rica", "code": "CR", "icon": "costarica.png"},
    {"name": "Cote D'Ivoire", "code": "CI", "icon": "ivorycoast.png"},
    {"name": "Croatia", "code": "HR", "icon": "croatia.png"},
    {"name": "Cuba", "code": "CU", "icon": "cuba.png"},
    {"name": "Cyprus", "code": "CY", "icon": "cyprus.png"},
    {"name": "Czech Republic", "code": "CZ", "icon": "czechrepublic.png"},
    {"name": "Denmark", "code": "DK", "icon": "denmark.png"},
    {"name": "Djibouti", "code": "DJ", "icon": "djibouti.png"},
    {"name": "Dominica", "code": "DM", "icon": "dominica.png"},
    {"name": "Dominican Republic", "code": "DO", "icon": "dominicanrepublic.png"},
    {"name": "Ecuador", "code": "EC", "icon": "ecuador.png"},
    {"name": "Egypt", "code": "EG", "icon": "egypt.png"},
    {"name": "El Salvador", "code": "SV", "icon": "elsalvador.png"},
    {"name": "Eritrea", "code": "ER", "icon": "eritrea.png"},
    {"name": "Estonia", "code": "EE", "icon": "estonia.png"},
    {"name": "Ethiopia", "code": "ET", "icon": "ethiopia.png"},
    {"name": "Falkland Islands (Malvinas)", "code": "FK", "icon": "falklandislands.png"},
    {"name": "Faroe Islands", "code": "FO", "icon": "faroeislands.png"},
    {"name": "Fiji", "code": "FJ", "icon": "fiji.png"},
    {"name": "Finland", "code": "FI", "icon": "finland.png"},
    {"name": "France", "code": "FR", "icon": "france.png"},
    {"name": "French Polynesia", "code": "PF", "icon": "frenchpolynesia.png"},
    {"name": "Gabon", "code": "GA", "icon": "gabon.png"},
    {"name": "Gambia", "code": "GM", "icon": "gambia.png"},
    {"name": "Georgia", "code": "GE", "icon": "georgia.png"},
    {"name": "Germany", "code": "DE", "icon": "germany.png"},
    {"name": "Ghana", "code": "GH", "icon": "ghana.png"},
    {"name": "Gibraltar", "code": "GI", "icon": "gibraltar.png"},
    {"name": "Greece", "code": "GR", "icon": "greece.png"},
    {"name": "Greenland", "code": "GL", "icon": "greenland.png"},
    {"name": "Grenada", "code": "GD", "icon": "grenada.png"},
    {"name": "Guadeloupe", "code": "GP", "icon": "guadeloupe.png"},
    {"name": "Guam", "code": "GU", "icon": "guam.png"},
    {"name": "Guatemala", "code": "GT", "icon": "guatemala.png"},
    {"name": "Guernsey", "code": "GG", "icon": "guernsey.png"},
    {"name": "Guinea", "code": "GN", "icon": "guinea.png"},
    {"name": "GuineaBissau", "code": "GW", "icon": "guineabissau.png"},
    {"name": "Guyana", "code": "GY", "icon": "guyana.png"},
    {"name": "Haiti", "code": "HT", "icon": "haiti.png"},
    {"name": "Honduras", "code": "HN", "icon": "honduras.png"},
    {"name": "Hong Kong", "code": "HK", "icon": "hongkong.png"},
    {"name": "Hungary", "code": "HU", "icon": "hungary.png"},
    {"name": "Iceland", "code": "IS", "icon": "iceland.png"},
    {"name": "India", "code": "IN", "icon": "india.png"},
    {"name": "Indonesia", "code": "ID", "icon": "indonesia.png"},
    {"name": "Iran, Islamic Republic Of", "code": "IR", "icon": "iran.png"},
    {"name": "Iraq", "code": "IQ", "icon": "iraq.png"},
    {"name": "Ireland", "code": "IE", "icon": "ireland.png"},
    {"name": "Isle of Man", "code": "IM", "icon": "isleofman.png"},
    {"name": "Israel", "code": "IL", "icon": "israel.png"},
    {"name": "Italy", "code": "IT", "icon": "italy.png"},
    {"name": "Jamaica", "code": "JM", "icon": "jamaica.png"},
    {"name": "Japan", "code": "JP", "icon": "japan.png"},
    {"name": "Jersey", "code": "JE", "icon": "jersey.png"},
    {"name": "Jordan", "code": "JO", "icon": "jordan.png"},
    {"name": "Kazakhstan", "code": "KZ", "icon": "kazakhstan.png"},
    {"name": "Kenya", "code": "KE", "icon": "kenya.png"},
    {"name": "Kiribati", "code": "KI", "icon": "kiribati.png"},
    {"name": "Korea, Democratic People'S Republic of", "code": "KP", "icon": "southkorea.png"},
    {"name": "Korea, Republic of", "code": "KR", "icon": "northkorea.png"},
    {"name": "Kuwait", "code": "KW", "icon": "kuwait.png"},
    {"name": "Kyrgyzstan", "code": "KG", "icon": "kyrgyzstan.png"},
    {"name": "Lao People'S Democratic Republic", "code": "LA", "icon": "laos.png"},
    {"name": "Latvia", "code": "LV", "icon": "latvia.png"},
    {"name": "Lebanon", "code": "LB", "icon": "lebanon.png"},
    {"name": "Lesotho", "code": "LS", "icon": "lesotho.png"},
    {"name": "Liberia", "code": "LR", "icon": "liberia.png"},
    {"name": "Libyan Arab Jamahiriya", "code": "LY", "icon": "libya.png"},
    {"name": "Liechtenstein", "code": "LI", "icon": "liechtenstein.png"},
    {"name": "Lithuania", "code": "LT", "icon": "lithuania.png"},
    {"name": "Luxembourg", "code": "LU", "icon": "luxembourg.png"},
    {"name": "Macao", "code": "MO", "icon": "macao.png"},
    {"name": "Macedonia, The Former Yugoslav Republic of", "code": "MK", "icon": "republicofmacedonia.png"},
    {"name": "Madagascar", "code": "MG", "icon": "madagascar.png"},
    {"name": "Malawi", "code": "MW", "icon": "malawi.png"},
    {"name": "Malaysia", "code": "MY", "icon": "malaysia.png"},
    {"name": "Maldives", "code": "MV", "icon": "maldives.png"},
    {"name": "Mali", "code": "ML", "icon": "mali.png"},
    {"name": "Malta", "code": "MT", "icon": "malta.png"},
    {"name": "Marshall Islands", "code": "MH", "icon": "marshallisland.png"},
    {"name": "Martinique", "code": "MQ", "icon": "martinique.png"},
    {"name": "Mauritania", "code": "MR", "icon": "mauritania.png"},
    {"name": "Mauritius", "code": "MU", "icon": "mauritius.png"},
    {"name": "Mayotte", "code": "YT", "icon": "mayotte.png"},
    {"name": "Mexico", "code": "MX", "icon": "mexico.png"},
    {"name": "Micronesia, Federated States of", "code": "FM", "icon": "micronesia.png"},
    {"name": "Moldova, Republic of", "code": "MD", "icon": "moldova.png"},
    {"name": "Monaco", "code": "MC", "icon": "monaco.png"},
    {"name": "Mongolia", "code": "MN", "icon": "mongolia.png"},
    {"name": "Montserrat", "code": "MS", "icon": "montserrat.png"},
    {"name": "Morocco", "code": "MA", "icon": "morocco.png"},
    {"name": "Mozambique", "code": "MZ", "icon": "mozambique.png"},
    {"name": "Myanmar", "code": "MM", "icon": "myanmar.png"},
    {"name": "Namibia", "code": "NA", "icon": "namibia.png"},
    {"name": "Nauru", "code": "NR", "icon": "nauru.png"},
    {"name": "Nepal", "code": "NP", "icon": "nepal.png"},
    {"name": "Netherlands", "code": "NL", "icon": "netherlands.png"},
    {"name": "New Zealand", "code": "NZ", "icon": "newzealand.png"},
    {"name": "Nicaragua", "code": "NI", "icon": "nicaragua.png"},
    {"name": "Niger", "code": "NE", "icon": "niger.png"},
    {"name": "Nigeria", "code": "NG", "icon": "nigeria.png"},
    {"name": "Niue", "code": "NU", "icon": "niue.png"},
    {"name": "Norfolk Island", "code": "NF", "icon": "norfolkisland.png"},
    {"name": "Northern Mariana Islands", "code": "MP", "icon": "northenmarianasislands.png"},
    {"name": "Norway", "code": "NO", "icon": "norway.png"},
    {"name": "Oman", "code": "OM", "icon": "oman.png"},
    {"name": "Pakistan", "code": "PK", "icon": "pakistan.png"},
    {"name": "Palau", "code": "PW", "icon": "palau.png"},
    {"name": "Palestine", "code": "PS", "icon": "palestine.png"},
    {"name": "Panama", "code": "PA", "icon": "panama.png"},
    {"name": "Papua New Guinea", "code": "PG", "icon": "papuanewguinea.png"},
    {"name": "Paraguay", "code": "PY", "icon": "paraguay.png"},
    {"name": "Peru", "code": "PE", "icon": "peru.png"},
    {"name": "Philippines", "code": "PH", "icon": "philippines.png"},
    {"name": "Pitcairn", "code": "PN", "icon": "pitcairnislands.png"},
    {"name": "Poland", "code": "PL", "icon": "poland.png"},
    {"name": "Portugal", "code": "PT", "icon": "portugal.png"},
    {"name": "Puerto Rico", "code": "PR", "icon": "puertorico.png"},
    {"name": "Qatar", "code": "QA", "icon": "qatar.png"},
    {"name": "Romania", "code": "RO", "icon": "romania.png"},
    {"name": "Russian Federation", "code": "RU", "icon": "russia.png"},
    {"name": "Rwanda", "code": "RW", "icon": "rwanda.png"},
    {"name": "Saint Kitts and Nevis", "code": "KN", "icon": "saintkittsandnevis.png"},
    {"name": "Saint Lucia", "code": "LC", "icon": "stlucia.png"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC", "icon": "stvincentandthegrenadines.png"},
    {"name": "Samoa", "code": "WS", "icon": "samoa.png"},
    {"name": "San Marino", "code": "SM", "icon": "sanmarino.png"},
    {"name": "Sao Tome and Principe", "code": "ST", "icon": "saotomeandprincipe.png"},
    {"name": "Saudi Arabia", "code": "SA", "icon": "saudiarabia.png"},
    {"name": "Senegal", "code": "SN", "icon": "senegal.png"},
    {"name": "Serbia", "code": "CS", "icon": "serbia.png"},
    {"name": "Montenegro", "code": "CS", "icon": "montenegro.png"},
    {"name": "Seychelles", "code": "SC", "icon": "seychelles.png"},
    {"name": "Sierra Leone", "code": "SL", "icon": "sierreleone.png"},
    {"name": "Singapore", "code": "SG", "icon": "singapore.png"},
    {"name": "Slovakia", "code": "SK", "icon": "slovakia.png"},
    {"name": "Slovenia", "code": "SI", "icon": "slovenia.png"},
    {"name": "Solomon Islands", "code": "SB", "icon": "solomonislands.png"},
    {"name": "Somalia", "code": "SO", "icon": "somalia.png"},
    {"name": "South Africa", "code": "ZA", "icon": "southafrica.png"},
    {"name": "South Georgia and the South Sandwich Islands", "code": "GS", "icon": "georgia.png"},
    {"name": "Spain", "code": "ES", "icon": "spain.png"},
    {"name": "Sri Lanka", "code": "LK", "icon": "srilanka.png"},
    {"name": "Sudan", "code": "SD", "icon": "sudan.png"},
    {"name": "Suriname", "code": "SR", "icon": "suriname.png"},
    {"name": "Swaziland", "code": "SZ", "icon": "swaziland.png"},
    {"name": "Sweden", "code": "SE", "icon": "sweden.png"},
    {"name": "Switzerland", "code": "CH", "icon": "switzerland.png"},
    {"name": "Syrian Arab Republic", "code": "SY", "icon": "syria.png"},
    {"name": "Taiwan, Province of China", "code": "TW", "icon": "taiwan.png"},
    {"name": "Tajikistan", "code": "TJ", "icon": "tajikistan.png"},
    {"name": "Tanzania, United Republic of", "code": "TZ", "icon": "tanzania.png"},
    {"name": "Thailand", "code": "TH", "icon": "thailand.png"},
    {"name": "Togo", "code": "TG", "icon": "togo.png"},
    {"name": "Tokelau", "code": "TK", "icon": "tokelau.png"},
    {"name": "Tonga", "code": "TO", "icon": "tonga.png"},
    {"name": "Trinidad and Tobago", "code": "TT", "icon": "trinidadandtobago.png"},
    {"name": "Tunisia", "code": "TN", "icon": "tunisia.png"},
    {"name": "Turkey", "code": "TR", "icon": "turkey.png"},
    {"name": "Turkmenistan", "code": "TM", "icon": "turkmenistan.png"},
    {"name": "Turks and Caicos Islands", "code": "TC", "icon": "turksandcaicos.png"},
    {"name": "Tuvalu", "code": "TV", "icon": "tuvalu.png"},
    {"name": "Uganda", "code": "UG", "icon": "uganda.png"},
    {"name": "Ukraine", "code": "UA", "icon": "ukraine.png"},
    {"name": "United Arab Emirates", "code": "AE", "icon": "unitedarabemirates.png"},
    {"name": "United Kingdom", "code": "GB", "icon": "unitedkingdom.png"},
    {"name": "United States", "code": "US", "icon": "unitedstates.png"},
    {"name": "Uruguay", "code": "UY", "icon": "uruguay.png"},
    {"name": "Uzbekistan", "code": "UZ", "icon": "uzbekistan.png"},
    {"name": "Vanuatu", "code": "VU", "icon": "vanuatu.png"},
    {"name": "Venezuela", "code": "VE", "icon": "venezuela.png"},
    {"name": "Viet Nam", "code": "VN", "icon": "vietnam.png"},
    {"name": "Virgin Islands", "code": "VG", "icon": "virginislands.png"},
    {"name": "Wales", "code": "WF", "icon": "wales.png"},
    {"name": "Western Sahara", "code": "EH", "icon": "westernsahara.png"},
    {"name": "Yemen", "code": "YE", "icon": "yemen.png"},
    {"name": "Zambia", "code": "ZM", "icon": "zambia.png"},
    {"name": "Zimbabwe", "code": "ZW", "icon": "zimbabwe.png"}
    ]