export const ADD_CLIENT_UID = "ADD_CLIENT_UID";

export const OPEN_CLOSE_MODAL = "OPEN_CLOSE_MODAL";

export const SEARCH_CLIENT_PROJECTS = "SEARCH_CLIENT_PROJECTS";

export const PROJECTS_PAGE_IS_FETCHING = "PROJECTS_PAGE_IS_FETCHING";

export const HEADER_IS_FETCHING = "HEADER_IS_FETCHING";

export const ADD_PROJECT_PAGE_IS_FETCHING = "ADD_PROJECT_PAGE_IS_FETCHING";

export const LOGIN_PAGE_IS_FETCHING = "LOGIN_PAGE_IS_FETCHING";

export const REGISTER_PAGE_IS_FETCHING = "REGISTER_PAGE_IS_FETCHING";

export const LOGOUT = "LOGOUT";