export const ADD_CLIENT_UID = "ADD_CLIENT_UID";

export const OPEN_CLOSE_MODAL = "OPEN_CLOSE_MODAL";

export const OPEN_CLOSE_ASIDE = "OPEN_CLOSE_ASIDE";

export const SHOW_ASIDE_BUTTONS = "SHOW_ASIDE_BUTTONS";

export const SEARCH_CLIENT_PROJECTS = "SEARCH_CLIENT_PROJECTS";

export const PROJECTS_PAGE_IS_FETCHING = "PROJECTS_PAGE_IS_FETCHING";

export const SET_PROJECT_ID = "SET_PROJECT_ID";

export const HEADER_IS_FETCHING = "HEADER_IS_FETCHING";

export const ADD_PROJECT_PAGE_IS_FETCHING = "ADD_PROJECT_PAGE_IS_FETCHING";

export const ADD_ATOMS_PAGE_IS_FETCHING = "ADD_ATOMS_PAGE_IS_FETCHING";

export const ATOMS_SECTION_IS_FETCHING = "ATOMS_SECTION_IS_FETCHING";

export const LOGIN_PAGE_IS_FETCHING = "LOGIN_PAGE_IS_FETCHING";

export const REGISTER_PAGE_IS_FETCHING = "REGISTER_PAGE_IS_FETCHING";

export const LOGOUT = "LOGOUT";

export const ADD_USER_TYPE = "ADD_USER_TYPE";

export const EMAIL_VERIFIED = "EMAIL_VERIFIED";

export const CHOOSED_USER_TYPE = "CHOOSED_USER_TYPE";

export const REDIRECT = "REDIRECT";

export const CHOOSED_BASIC_INPUT = "CHOOSED_BASIC_INPUT";